// SleepTracker.Vue/src/components/SleepList.vue
<script setup lang="ts">
import {ref, onMounted, onUnmounted} from 'vue';
import {getSleeps, createSleep, updateSleep, deleteSleep} from '../services/sleep';
import type {SleepReadDto, SleepCreateDto, SleepUpdateDto} from '../services/sleep';
import {useToast} from '../composables/useToast';

const {show: showToast} = useToast();

const sleeps = ref<SleepReadDto[]>([]);
const loading = ref(false);
const error = ref<string | null>(null);

const pageNumber = ref(1);
const pageSize = ref(10);
const totalRecords = ref(0);
const totalPages = ref(0);

const timerRunning = ref(false);
const timerStartTime = ref<Date |null>(null);
const elapsedTime = ref('00:00:00');
let timerInterval: any = null;

const filterStartDate = ref<Date | null>(null);
const filterEndDate = ref<Date | null>(null);

const showCreateModal = ref(false);
const createForm = ref<{start: string; end: string}>({start: '', end: ''});

const showEditModal = ref(false);
const editSleep = ref<SleepReadDto | null>(null);
const editForm = ref<{start: string; end: string}>({start: '', end: ''});

const showDeleteModal = ref(false)
const sleepToDelete = ref<SleepReadDto | null>(null)

function openDeleteModal(sleep: SleepReadDto) {
  sleepToDelete.value = sleep
  showDeleteModal.value = true
}

function closeDeleteModal() {
  showDeleteModal.value = false
  sleepToDelete.value = null
}

async function confirmDelete() {
  if (!sleepToDelete.value) return
  try {
    await deleteSleep(sleepToDelete.value.id)
    closeDeleteModal()
    loadSleeps()
    showToast('Sleep record deleted.', 'success');
  } catch (err) {
    console.error('Error deleting sleep: ', err)
    showToast('Failed to delete sleep record. Please try again.', 'error');
  }
}

async function loadSleeps() {
  loading.value = true;
  error.value = null;

  try {
    const response = await getSleeps(
      pageNumber.value,
      pageSize.value,
      filterStartDate.value || undefined,
      filterEndDate.value || undefined
    );

    if (response.status === 0 && response.data) {
      sleeps.value = response.data;
      totalRecords.value = response.totalRecords;
      totalPages.value = response.totalPages;
    } else {
      error.value = response.message || 'Failed to load sleep records';
    }
  } catch (err) {
    error.value = 'Failed to load sleep records. Please try again.';
    console.error('Error loading sleeps: ', err);
  } finally {
    loading.value = false;
  }
}

onMounted(() => {
  loadSleeps();
});

onUnmounted(() => {
  if (timerInterval) {
    clearInterval(timerInterval);
  };
})

function onFilterChange() {
  pageNumber.value = 1;
  loadSleeps();
}

function clearFilters() {
  filterStartDate.value = null;
  filterEndDate.value = null;
  pageNumber.value = 1;
  loadSleeps();
}

function goToPreviousPage() {
  if (pageNumber.value <= 1) return;
  pageNumber.value--;
  loadSleeps();
}

function goToNextPage() {
  if (pageNumber.value >= totalPages.value) return;
  pageNumber.value++;
  loadSleeps();
}

function goToFirstPage() {
  if (pageNumber.value <= 1) return;
  pageNumber.value = 1;
  loadSleeps();
}

function goToLastPage() {
  if (pageNumber.value >= totalPages.value) return;
  pageNumber.value = totalPages.value;
  loadSleeps();
}

function startSleepTimer() {
  const startTime = new Date();
  timerStartTime.value = startTime;
  timerRunning.value = true;
  elapsedTime.value = '00:00:00';

  timerInterval = setInterval(() => {
    if (timerStartTime.value) {
      const now = new Date();
      const elapsed = Math.floor((now.getTime() - timerStartTime.value.getTime()) / 1000);
      elapsedTime.value = formatElapsedTime(elapsed);
    }
  }, 1000);
}

function stopSleepTimer() {
  if (!timerStartTime.value) {
    return;
  }

  if (timerInterval) {
    clearInterval(timerInterval);
    timerInterval = null;
  }

  const startTime = timerStartTime.value;
  const endTime = new Date();

  const createDto: SleepCreateDto = {
    start: startTime.toISOString(),
    end: endTime.toISOString()
  };

  createSleep(createDto)
    .then(() => {
      timerRunning.value = false;
      timerStartTime.value = null;
      elapsedTime.value = '00:00:00';
      loadSleeps();
      showToast('Sleep record saved.', 'success');
    })
    .catch((err) => {
      showToast('Failed to save sleep record.', 'error');
    });
}

function formatElapsedTime(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = seconds % 60;
  return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
}

function formatDateTime(dateTimeString: string): string {
  const date = new Date(dateTimeString);
  return date.toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    hour12: true
  });
}

function formatDuration(start: string, end: string): string {
  const startDate = new Date(start);
  const endDate = new Date(end);
  const diffMs = endDate.getTime() - startDate.getTime();
  const diffSeconds = Math.floor(diffMs / 1000);
  const diffMinutes = Math.floor(diffSeconds / 60);
  const hours = Math.floor(diffMinutes / 60);
  const minutes = diffMinutes % 60;
  const seconds = diffSeconds % 60;

  if (diffSeconds < 60) {
    return `${seconds} second${seconds !== 1 ? 's' : ''}`;
  } else if (hours === 0) {
    return `${minutes} minute${minutes !== 1 ? 's' : ''}`;
  } else if (minutes === 0) {
    return `${hours} hour${hours !== 1 ? 's' : ''}`;
  } else {
    return `${hours} hour${hours !== 1 ? 's' : ''} and ${minutes} minute${minutes !== 1 ? 's' : ''}`;
  }
}

function toDateTimeLocal(isoString: string): string {
  const d = new Date(isoString);
  const pad = (n: number) => n.toString().padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

function fromDateTimeLocal(dateTimeLocal: string): string {
  return new Date(dateTimeLocal).toISOString();
}

function isStartBeforeEnd(startDateTimeLocal: string, endDateTimeLocal: string): boolean {
  if (!startDateTimeLocal || !endDateTimeLocal) return true;
  return new Date(startDateTimeLocal).getTime() < new Date(endDateTimeLocal).getTime();
}

function openCreateModal() {
  const now = new Date();
  createForm.value = {
    start: toDateTimeLocal(now.toISOString()),
    end: toDateTimeLocal(now.toISOString())
  };
  showCreateModal.value = true;
}

function closeCreateModal() {
  showCreateModal.value = false;
}

async function submitCreate() {
  if (!isStartBeforeEnd(createForm.value.start, createForm.value.end)) {
    showToast('Start time must be earlier than end time.', 'error');
    return;
  }
  try {
    await createSleep({
      start: fromDateTimeLocal(createForm.value.start),
      end: fromDateTimeLocal(createForm.value.end)
    });
    closeCreateModal();
    loadSleeps();
    showToast('Sleep record saved.', 'success');
  } catch (err) {
    console.error('Error creating sleep: ', err);
    showToast('Failed to create sleep record. Please try again.', 'error');
  }
}

function openEditModal(sleep: SleepReadDto) {
  editSleep.value = sleep;
  editForm.value = {
    start: toDateTimeLocal(sleep.start),
    end: toDateTimeLocal(sleep.end)
  };
  showEditModal.value = true;
}

function closeEditModal() {
  showEditModal.value = false;
  editSleep.value = null;
}

async function submitEdit() {
  if (!editSleep.value) return;
  if (!isStartBeforeEnd(editForm.value.start, editForm.value.end)){
    showToast('Start time must be earlier than end time.', 'error');
    return;
  }
  try {
    await updateSleep(editSleep.value.id, {
      start: fromDateTimeLocal(editForm.value.start),
      end: fromDateTimeLocal(editForm.value.end)
    });
    closeEditModal();
    loadSleeps();
    showToast('Sleep record updated.', 'success');
  } catch (err) {
    console.error('Error updating sleep: ', err);
    showToast('Failed to update sleep record. Please try again.', 'error');
  }
}

async function deleteSleepRecord(sleep: SleepReadDto) {
  openDeleteModal(sleep)
}
</script>

<template>
  <div class="sleep-list-container">

    <div class="header-section flex flex-col gap-4 md:flex-row md:items-center md:justify-between mb-6">
      <div class="filter-section">
        <div class="filter-fields flex flex-row flex-wrap gap-2 items-center">
          <div class="flex flex-col gap-1 w-36 min-w-0 md:w-auto">
            <label for="filter-start">Sleep Date From</label>
            <input
              id="filter-start"
              type="date"
              class="input input-bordered pr-2"
              :value="filterStartDate ? filterStartDate.toISOString().slice(0, 10) : ''"
              @change="filterStartDate = ($event.target as HTMLInputElement).value ? new Date(($event.target as HTMLInputElement).value) : null; onFilterChange()"
            />
          </div>
          <div class="flex flex-col gap-1 w-36 min-w-0 md:w-auto">
            <label for="filter-end">Sleep Date To</label>
            <input
              id="filter-end"
              type="date"
              class="input input-bordered pr-2"
              :value="filterEndDate ? filterEndDate.toISOString().slice(0, 10) : ''"
              @change="filterEndDate = ($event.target as HTMLInputElement).value ? new Date(($event.target as HTMLInputElement).value) : null; onFilterChange()"
            />
          </div>
          <button v-if="filterStartDate || filterEndDate" type="button" class="btn btn-ghost btn-sm btn-circle text-error flex-shrink-0 ring-1 ring-error/25 !w-7 !h-7 !min-h-0 !min-w-0 p-0 flex items-center justify-center" @click="clearFilters">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>

      <div class="header-actions">
        <button v-if="!timerRunning" type="button" @click="startSleepTimer" class="btn btn-primary">Start Sleep Timer</button>
        <template v-else>
          <span class="timer-text">{{ elapsedTime }}</span>
          <button type="button" @click="stopSleepTimer" class="btn btn-error">Stop</button>
        </template>
        <button type="button" @click="openCreateModal" class="btn btn-primary">Add Sleep Record</button>
      </div>
    </div>

    <div v-if="loading" class="loading-container">
      <p>Loading sleep records...</p>
    </div>

    <div v-if="error" class="error-container">
      <p>{{ error }}</p>
    </div>

    <div v-if="!loading && !error && sleeps.length > 0" class="table-container">
      <div class="table-container overflow-x-auto mb-4 hidden md:block">
        <table class="table table-zebra">
          <thead>
            <tr>
              <th>Sleep Date/Time</th>
              <th>Wake Date/Time</th>
              <th>Duration</th>
              <th class="actions-column">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="sleep in sleeps" :key="sleep.id">
              <td>{{ formatDateTime(sleep.start) }}</td>
              <td>{{ formatDateTime(sleep.end) }}</td>
              <td>{{ formatDuration(sleep.start, sleep.end) }}</td>
              <td class="actions-column">
                <button type="button" @click="openEditModal(sleep)" aria-label="Edit" class="btn btn-sm btn-ghost btn-circle">
                  <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                  </svg>
                </button>
                <button type="button" @click="deleteSleepRecord(sleep)" aria-label="Delete" class="btn btn-sm btn-error btn-circle">
                  <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="block md:hidden space-y-4">
        <div
          v-for="sleep in sleeps"
          :key="sleep.id"
          class="card bg-base-200 shadow compact"
        >
          <div class="card-body gap-1">
            <div class="flex justify-between gap-2">
              <span class="font-medium text-base-content/70">Sleep Date/Time</span>
              <span>{{ formatDateTime(sleep.start) }}</span>
            </div>
            <div class="flex justify-between gap-2">
              <span class="font-medium text-base-content/70">Wake Date/Time</span>
              <span>{{ formatDateTime(sleep.end) }}</span>
            </div>
            <div class="flex justify-between gap-2">
              <span class="font-medium text-base-content/70">Duration</span>
              <span>{{ formatDuration(sleep.start, sleep.end) }}</span>
            </div>
            <div class="flex justify-end gap-2 pt-2">
              <button type="button" class="btn btn-sm btn-ghost btn-circle" aria-label="Edit sleep record" @click="openEditModal(sleep)">
                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                </svg>
              </button>
              <button type="button" class="btn btn-sm btn-error btn-circle" aria-label="Delete sleep record" @click="deleteSleepRecord(sleep)">
                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div v-if="!loading && !error && sleeps.length > 0" class="pagination-info">
      <p>Showing {{ sleeps.length }} of {{ totalRecords }} records (Page {{ pageNumber }} of {{ totalPages }})</p>
      <div v-if="totalPages > 1" class="pagination-buttons">
        <button
          type="button"
          :disabled="pageNumber <= 1"
          @click="goToFirstPage"
        >
        First
        </button>
        <button
          type="button"
          :disabled="pageNumber <= 1"
          @click="goToPreviousPage"
        >
        Previous  
        </button>
        <button
          type="button"
          :disabled="pageNumber >= totalPages"
          @click="goToNextPage"
        >
        Next
        </button>
        <button
          type="button"
          :disabled="pageNumber >= totalPages"
          @click="goToLastPage"
        >
        Last
        </button>
      </div>
    </div>

    <div v-if="!loading && !error && sleeps.length === 0" class="empty-state">
      <p>No sleep records found.</p>
    </div>

    <div class="modal" :class="{ 'modal-open': showCreateModal }">
      <div class="modal-box">
        <h3 class="font-bold text-lg">Add Sleep Record</h3>
        <div class="form-control w-full gap-2 mt-4">
          <label for="create-start" class="label">
            <span class="label-text">Start</span>
          </label>
          <input
            id="create-start"
            v-model="createForm.start"
            type="datetime-local"
            class="input input-bordered w-full"
          />
          <label for="create-end" class="label">
            <span class="label-text">End</span>
          </label>
          <input
            id="create-end"
            v-model="createForm.end"
            type="datetime-local"
            class="input input-bordered w-full"
          />
        </div>
        <div class="modal-action">
          <button type="button" class="btn btn-ghost" @click="closeCreateModal">Cancel</button>
          <button type="button" class="btn btn-primary" @click="submitCreate">Save</button>
        </div>
      </div>
      <form method="dialog" class="modal-backdrop" @submit="closeCreateModal">
        <button type="submit">close</button>
      </form>
    </div>

    <div class="modal" :class="{ 'modal-open': showEditModal }">
      <div class="modal-box">
        <h3 class="font-bold text-lg">Edit Sleep Record</h3>
        <div class="form-control w-full gap-2 mt-4">
          <label for="edit-start" class="label">
            <span class="label-text">Start</span>
          </label>
          <input
            id="edit-start"
            v-model="editForm.start"
            type="datetime-local"
            class="input input-bordered w-full"
          />
          <label for="edit-end" class="label">
            <span class="label-text">End</span>
          </label>
          <input
            id="edit-end"
            v-model="editForm.end"
            type="datetime-local"
            class="input input-bordered w-full"
          />
        </div>
        <div class="modal-action">
          <button type="button" class="btn btn-ghost" @click="closeEditModal">Cancel</button>
          <button type="button" class="btn btn-primary" @click="submitEdit">Save</button>
        </div>
      </div>
      <form method="dialog" class="modal-backdrop" @submit="closeEditModal">
        <button type="submit">close</button>
      </form>
    </div>

    <div class="modal" :class="{ 'modal-open': showDeleteModal }">
      <div class="modal-box">
        <h3 class="font-bold text-lg">Delete Sleep Record?</h3>
        <p class="py-2">Are you sure you want to delete this sleep record? This cannot be undone.</p>
        <template v-if="sleepToDelete">
          <div class="rounded-lg bg-base-300 p-3 text-sm space-y-1">
            <p><span class="font-medium">Start:</span> {{ formatDateTime(sleepToDelete.start) }}</p>
            <p><span class="font-medium">End:</span> {{ formatDateTime(sleepToDelete.end) }}</p>
            <p><span class="font-medium">Duration:</span> {{ formatDuration(sleepToDelete.start, sleepToDelete.end) }}</p>
          </div>
        </template>
        <div class="modal-action">
          <button type="button" class="btn btn-ghost" @click="closeDeleteModal">Cancel</button>
          <button type="button" class="btn btn-error" @click="confirmDelete">Delete</button>
        </div>
      </div>
      <form method="dialog" class="modal-backdrop" @submit="closeDeleteModal">
        <button type="submit">close</button>
      </form>
    </div>

  </div>
</template>

<style scoped>
.modal-form {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  margin: 1rem 0;
}

.modal-form label {
  font-weight: 500;
}

.pagination-buttons {
  display: flex;
  gap: 0.5rem;
  justify-content: center;
  margin-top: 0.5rem;
}

.pagination-info {
  margin-top: 1rem;
  text-align: center;
  font-size: 0.875rem;
  color: #6b7280;
}

.empty-state {
  padding: 2rem;
  text-align: center;
  color: #6b7280;
}

.table-container {
  overflow-x: auto;
  margin-bottom: 1rem;
}

.actions-column {
  white-space: nowrap;
}

.filter-fields {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  align-items: center;
}

.header-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  align-items: center;
}

.timer-text {
  font-family: monospace;
  font-weight: 500;
}

.sleep-list-container {
  padding: 1rem;
}

.loading-container,
.error-container {
  padding: 2rem;
  text-align: center;
}

.error-container {
  color: #b91c1c;
}
</style>

// SleepTracker.React/src/components/SleepList.tsx
import {useState, useEffect, useRef} from 'react';
import { getSleeps, createSleep, updateSleep, deleteSleep } from '../services/sleep';
import { useToast } from '../contexts/ToastContext';
import type { SleepReadDto } from '../services/sleep';

export function SleepList() {
  const [sleeps, setSleeps] = useState<SleepReadDto[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [pageNumber, setPageNumber] = useState(1);
  const [pageSize] = useState(10);
  const [totalRecords, setTotalRecords] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [filterStartDate, setFilterStartDate] = useState<Date | null>(null);
  const [filterEndDate, setFilterEndDate] = useState<Date | null>(null);
  const [timerRunning, setTimerRunning] = useState(false);
  const [elapsedTime, setElapsedTime] = useState('00:00:00');
  const [timerStartTime, setTimerStartTime] = useState<Date | null>(null);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [createForm, setCreateForm] = useState({start: '', end: ''});
  const [createFormError, setCreateFormError] = useState<string | null>(null);
  const [showEditModal, setShowEditModal] = useState(false);
  const [editSleep, setEditSleep] = useState<SleepReadDto | null>(null);
  const [editForm, setEditForm] = useState({start: '', end: ''});
  const [editFormError, setEditFormError] = useState<string | null>(null);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [sleepToDelete, setSleepToDelete] = useState<SleepReadDto | null>(null);
  const timerIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const {show: showToast} = useToast();

  async function loadSleeps() {
    setLoading(true);
    setError(null);
    try {
      const response = await getSleeps(
        pageNumber, 
        pageSize,
        filterStartDate ?? undefined,
        filterEndDate ?? undefined
      );
      if (response.status === 0 && response.data) {
        setSleeps(response.data);
        setTotalRecords(response.totalRecords);
        setTotalPages(response.totalPages);
      } else {
        setError(response.message || 'Failed to load sleep records');
      }
    } catch (err) {
      setError('Failed to load sleep records. Please try again.');
      console.error('Error loading sleeps: ', err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadSleeps();
    return () => {
      if (timerIntervalRef.current) {
        clearInterval(timerIntervalRef.current);
      }
    };
  }, [pageNumber, filterStartDate, filterEndDate]);

  function formatDateTime(dateTimeString: string): string {
    const date = new Date(dateTimeString);
    return date.toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true
    });
  }

  function formatDuration(start: string, end: string): string {
    const startDate = new Date(start);
    const endDate = new Date(end);
    const diffMs = endDate.getTime() - startDate.getTime();
    const diffSeconds = Math.floor(diffMs / 1000);
    const diffMinutes = Math.floor(diffSeconds / 60);
    const hours = Math.floor(diffMinutes / 60);
    const minutes = diffMinutes % 60;
    const seconds = diffSeconds % 60;
    if (diffSeconds < 60) {
      return `${seconds} second${seconds !== 1 ? 's' : ''}`;
    } else if (hours === 0) {
      return `${minutes} minute${minutes !== 1 ? 's' : ''}`;
    } else if (minutes === 0) {
      return `${hours} hour${hours !== 1 ? 's' : ''}`;
    } else {
      return `${hours} hour${hours !== 1 ? 's' : ''} and ${minutes} minute${minutes !== 1 ? 's' : ''}`;
    }
  }

  function formatElapsedTime(seconds: number): string {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = seconds % 60;
    const pad = (n: number) => n.toString().padStart(2, '0');
    return `${pad(h)}:${pad(m)}:${pad(s)}`;
  }

  function toDateTimeLocal(isoString: string): string {
    const d = new Date(isoString);
    const pad = (n: number) => n.toString().padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
  }

  function fromDateTimeLocal(dateTimeLocal: string): string {
    return new Date(dateTimeLocal).toISOString();
  }

  function isStartBeforeEnd(start: string, end: string): boolean {
    if (!start || !end) return true;
    return new Date(start).getTime() < new Date(end).getTime();
  }

  async function submitCreate() {
    if (!isStartBeforeEnd(createForm.start, createForm.end)) {
      setCreateFormError('Start time must be earlier than end time.');
      return;
    }
    try {
      setCreateFormError(null);
      await createSleep({
        start: fromDateTimeLocal(createForm.start),
        end: fromDateTimeLocal(createForm.end)
      });
      setShowCreateModal(false);
      loadSleeps();
      showToast('Sleep record saved.', 'success');
    } catch (err) {
      console.error('Error creating sleep: ', err);
      showToast('Failed to create sleep record. Please try again.', 'error');
    }
  }

  async function submitEdit() {
    if (!editSleep) return;
    if (!isStartBeforeEnd(editForm.start, editForm.end)) {
      setEditFormError('Start time must be earlier than end time.');
      return;
    }
    setEditFormError(null);
    try {
      await updateSleep(editSleep.id, {
        start: fromDateTimeLocal(editForm.start),
        end: fromDateTimeLocal(editForm.end)
      });
      closeEditModal();
      loadSleeps();
      showToast('Sleep record updated.', 'success');
    } catch (err) {
      console.error('Error updating sleep: ', err);
      showToast('Failed to update sleep record. Please try again.', 'error');
    }
  }

  function stopSleepTimer() {
    if (!timerStartTime) return;
    if (timerIntervalRef.current) {
      clearInterval(timerIntervalRef.current);
      timerIntervalRef.current = null;
    }
    const endTime = new Date();
    createSleep({
      start: timerStartTime.toISOString(),
      end: endTime.toISOString()
    })
      .then(() => {
        setTimerRunning(false);
        setTimerStartTime(null);
        setElapsedTime('00:00:00');
        loadSleeps();
        showToast('Sleep record saved.', 'success');
      })
      .catch(() => {
        showToast('Failed to save sleep record.', 'error');
      })
  }

  function openEditModal(sleep: SleepReadDto) {
    if (!sleep?.start || !sleep?.end) return;
    setEditSleep(sleep);
    setEditForm({
      start: toDateTimeLocal(sleep.start),
      end: toDateTimeLocal(sleep.end)
    });
    setEditFormError(null);
    setShowEditModal(true);
  }

  function closeEditModal() {
    setShowEditModal(false);
    setEditSleep(null);
  }

  function openDeleteModal(sleep: SleepReadDto) {
    setSleepToDelete(sleep);
    setShowDeleteModal(true);
  }

  function closeDeleteModal() {
    setShowDeleteModal(false);
    setSleepToDelete(null);
  }

  async function confirmDelete() {
    if (!sleepToDelete) return;
    try {
      await deleteSleep(sleepToDelete.id);
      closeDeleteModal();
      loadSleeps();
      showToast('Sleep record deleted.', 'success');
    } catch (err) {
      console.error('Error deleting sleep: ', err);
      showToast('Failed to delete sleep record. Please try again.', 'error');
    }
  }

  function goToFirstPage() {
    if (pageNumber <= 1) return;
    setPageNumber(1);
  }
  function goToPreviousPage() {
    if (pageNumber <= 1) return;
    setPageNumber(pageNumber - 1);
  }
  function goToNextPage() {
    if (pageNumber >= totalPages) return;
    setPageNumber(pageNumber + 1);
  }
  function goToLastPage() {
    if (pageNumber >= totalPages) return;
    setPageNumber(totalPages);
  }

  return (
    <div className="p-4 sleep-list-container">
      <div className="header-section flex flex-col gap-4 md:flex-row md:items-center md:justify-between mb-6">
        <div className="filter-section">
          <div className="filter-fields flex flex-wrap gap-2 items-center">
            <div className="flex flex-col gap-1 w-36 min-w-0 md:w-auto">
              <label htmlFor="filter-start">Sleep Date From</label>
              <input
                id="filter-start"
                type="date"
                className="input input-bordered pr-2 w-full"
                value={filterStartDate ? filterStartDate.toISOString().slice(0, 10) : ''}
                onChange={(e) => {
                  const val = e.target.value;
                  const nextStart = val ? new Date(val) : null;
                  setFilterStartDate(nextStart);
                  setPageNumber(1);
                  loadSleeps();
                }}
              />
            </div>
            <div className="flex flex-col gap-1 w-36 min-w-0 md:w-auto">
              <label htmlFor="filter-end">Sleep Date To</label>
              <input
                id="filter-end"
                type="date"
                className="input input-bordered pr-2 w-full"
                value={filterEndDate ? filterEndDate.toISOString().slice(0, 10) : ''}
                onChange={(e) => {
                  const val = e.target.value;
                  const nextEnd = val ? new Date(val) : null;
                  setFilterEndDate(nextEnd);
                  setPageNumber(1);
                  loadSleeps();
                }}
              />
            </div>
            {(filterStartDate || filterEndDate) && (
              <button
                type="button"
                className="btn btn-ghost btn-sm btn-circle text-error shrink-0 ring-1 ring-error/25 w-7 h-7 min-h-0 min-w-0 p-0 flex items-center justify-center"
                onClick={() => {
                  setFilterStartDate(null);
                  setFilterEndDate(null);
                  setPageNumber(1);
                  loadSleeps();
                }}
                aria-label="Clear filters"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            )}
          </div>
        </div>
        <div className="header-actions flex flex-wrap gap-2 items-center">
          {!timerRunning ? (
            <button
              type="button"
              onClick={() => {
                const startTime = new Date();
                setTimerStartTime(startTime);
                setTimerRunning(true);
                setElapsedTime('00:00:00');
                if (timerIntervalRef.current) clearInterval(timerIntervalRef.current);
                timerIntervalRef.current = setInterval(() => {
                  const elapsed = Math.floor((Date.now() - startTime.getTime()) / 1000);
                  setElapsedTime(formatElapsedTime(elapsed));
                }, 1000);
              }}
              className="btn btn-primary"
            >
              Start Sleep Timer
            </button>
          ) : (
            <>
              <span className="font-mono font-medium">{elapsedTime}</span>
              <button type="button" onClick={stopSleepTimer} className="btn btn-error">
                Stop
              </button>
            </>
          )}
          <button type="button"
            onClick={() => {
              const now = new Date();
              const local = toDateTimeLocal(now.toISOString());
              setCreateForm({start: local, end: local});
              setCreateFormError(null);
              setShowCreateModal(true);
            }}
            className="btn btn-primary">
            Add Sleep Record
          </button>
        </div>
      </div>

      {loading && <p>Loading sleep records...</p>}
      {error && <p className="text-error">{error}</p>}
      {!loading && !error && sleeps.length === 0 && (
        <p>No sleep records found.</p>
      )}
      {!loading && !error && sleeps.length > 0 && (
        <>
          <div className="table-container overflow-x-auto mb-4 hidden md:block">
            <table className="table table-zebra">
              <thead>
                <tr>
                  <th>Sleep Date/Time</th>
                  <th>Wake Date/Time</th>
                  <th>Duration</th>
                  <th className="actions-column">Actions</th>
                </tr>
              </thead>
              <tbody>
                {sleeps.map((sleep) => (
                  <tr key={sleep.id}>
                    <td>{formatDateTime(sleep.start)}</td>
                    <td>{formatDateTime(sleep.end)}</td>
                    <td>{formatDuration(sleep.start, sleep.end)}</td>
                    <td className="actions-column">
                      <button type="button" onClick={() => openEditModal(sleep)} aria-label="Edit" className="btn btn-sm btn-ghost btn-circle">
                        <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                        </svg>
                      </button>
                      <button type="button" onClick={() => openDeleteModal(sleep)} aria-label="Delete" className="btn btn-sm btn-error btn-circle">
                        <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                        </svg>
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="block md:hidden space-y-4">
            {sleeps.map((sleep) => (
              <div key={sleep.id} className="card bg-base-200 shadow compact">
                <div className="card-body gap-1">
                  <div className="flex justify-between gap-2">
                    <span className="font-medium text-base-content/70">Sleep Date/Time</span>
                    <span>{formatDateTime(sleep.start)}</span>
                  </div>
                  <div className="flex justify-between gap-2">
                    <span className="font-medium text-base-content/70">Wake Date/Time</span>
                    <span>{formatDateTime(sleep.end)}</span>
                  </div>
                  <div className="flex justify-between gap-2">
                    <span className="font-medium text-base-content/70">Duration</span>
                    <span>{formatDuration(sleep.start, sleep.end)}</span>
                  </div>
                  <div className="flex justify-end gap-2 pt-2">
                    <button type="button" className="btn btn-sm btn-ghost btn-circle" aria-label="Edit sleep record" onClick={() => openEditModal(sleep)}>
                      <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                      </svg>
                    </button>
                    <button type="button" className="btn btn-sm btn-error btn-circle" aria-label="Delete sleep record" onClick={() => openDeleteModal(sleep)}>
                      <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                      </svg>
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="pagination-info mt-4 text-center text-sm text-base-content/70">
            <p>Showing {sleeps.length} of {totalRecords} records (Page {pageNumber} of {totalPages})</p>
            {totalPages > 1 && (
              <div className="pagination-buttons flex gap-2 justify-center mt-2">
                <button type="button" disabled={pageNumber <= 1} onClick={goToFirstPage} className="btn btn-sm">First</button>
                <button type="button" disabled={pageNumber <= 1} onClick={goToPreviousPage} className="btn btn-sm">Previous</button>
                <button type="button" disabled={pageNumber >= totalPages} onClick={goToNextPage} className="btn btn-sm">Next</button>
                <button type="button" disabled={pageNumber >= totalPages} onClick={goToLastPage} className="btn btn-sm">Last</button>
              </div>
            )}
          </div>
        </>
      )}

      <div className={`modal ${showCreateModal ? 'modal-open' : ''}`}>
        <div className="modal-box">
          <h3 className="font-bold text-lg">Add Sleep Record</h3>
          <div className="form-control w-full gap-2 mt-4">
            <label htmlFor="create-start" className="label">
              <span className="label-text">Start</span>
            </label>
            <input
              id="create-start"
              type="datetime-local"
              className="input input-bordered w-full"
              value={createForm.start}
              onChange={(e) => {
                setCreateForm((prev) => ({ ...prev, start: e.target.value }));
                setCreateFormError(null);
              }}
              onBlur={() => {
                setCreateFormError(
                  createForm.start && createForm.end && !isStartBeforeEnd(createForm.start, createForm.end)
                    ? 'Start time must be earlier than end time.'
                    : null
                );
              }}
            />
            <label htmlFor="create-end" className="label">
              <span className="label-text">End</span>
            </label>
            <input
              id="create-end"
              type="datetime-local"
              className="input input-bordered w-full"
              value={createForm.end}
              onChange={(e) => {
                setCreateForm((prev) => ({ ...prev, end: e.target.value }));
                setCreateFormError(null);
              }}
              onBlur={() => {
                setCreateFormError(
                  createForm.start && createForm.end && !isStartBeforeEnd(createForm.start, createForm.end)
                    ? 'Start time must be earlier than end time.'
                    : null
                );
              }}
            />
            {createFormError && (<p className="text-error text-sm mt-1">{createFormError}</p>)}
          </div>
          <div className="modal-action">
            <button type="button" className="btn btn-ghost" onClick={() => setShowCreateModal(false)}>
              Cancel
            </button>
            <button type="button" onClick={submitCreate} className="btn btn-primary">
              Save
            </button>
          </div>
        </div>
        <form method="dialog" className="modal-backdrop">
          <button type="submit" onClick={() => setShowCreateModal(false)}>close</button>
        </form>
      </div>

      <div className={`modal ${showEditModal ? 'modal-open' : ''}`}>
        <div className="modal-box">
          <h3 className="font-bold text-lg">Edit Sleep Record</h3>
          <div className="form-control w-full gap-2 mt-4">
            <label htmlFor="edit-start" className="label">
              <span className="label-text">Start</span>
            </label>
            <input
              id="edit-start"
              type="datetime-local"
              className="input input-bordered w-full"
              value={editForm.start}
              onChange={(e) => {
                setEditForm((prev) => ({ ...prev, start: e.target.value }));
                setEditFormError(null);
              }}
              onBlur={() => {
                setEditFormError(
                  editForm.start && editForm.end && !isStartBeforeEnd(editForm.start, editForm.end)
                    ? 'Start time must be earlier than end time.'
                    : null
                );
              }}
            />
            <label htmlFor="edit-end" className="label">
              <span className="label-text">End</span>
            </label>
            <input
              id="edit-end"
              type="datetime-local"
              className="input input-bordered w-full"
              value={editForm.end}
              onChange={(e) => {
                setEditForm((prev) => ({ ...prev, end: e.target.value }));
                setEditFormError(null);
              }}
              onBlur={() => {
                setEditFormError(
                  editForm.start && editForm.end && !isStartBeforeEnd(editForm.start, editForm.end)
                    ? 'Start time must be earlier than end time.'
                    : null
                );
              }}
            />
            {editFormError && (
              <p className="text-error text-sm mt-1">{editFormError}</p>
            )}
          </div>
          <div className="modal-action">
            <button type="button" className="btn btn-ghost" onClick={closeEditModal}>
              Cancel
            </button>
            <button type="button" onClick={submitEdit} className="btn btn-primary">
              Save
            </button>
          </div>
        </div>
        <form method="dialog" className="modal-backdrop">
          <button type="submit" onClick={closeEditModal}>close</button>
        </form>
      </div>

      <div className={`modal ${showDeleteModal ? 'modal-open' : ''}`}>
        <div className="modal-box">
          <h3 className="font-bold text-lg">Delete Sleep Record?</h3>
          <p className="py-2">Are you sure you want to delete this sleep record? This cannot be undone.</p>
          {sleepToDelete && (
            <div className="rounded-lg bg-base-300 p-3 text-sm space-y-1">
              <p><span className="font-medium">Start:</span> {formatDateTime(sleepToDelete.start)}</p>
              <p><span className="font-medium">End:</span> {formatDateTime(sleepToDelete.end)}</p>
              <p><span className="font-medium">Duration:</span> {formatDuration(sleepToDelete.start, sleepToDelete.end)}</p>
            </div>
          )}
          <div className="modal-action">
            <button type="button" className="btn btn-ghost" onClick={closeDeleteModal}>
              Cancel
            </button>
            <button type="button" className="btn btn-error" onClick={confirmDelete}>
              Delete
            </button>
          </div>
        </div>
        <form method="dialog" className="modal-backdrop">
          <button type="submit" onClick={closeDeleteModal}>close</button>
        </form>
      </div>


    </div>
  );
}
